# Generated by Django 6.0.5 on 2026-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(default='Pelanggan', max_length=100),
        ),
    ]
