# Generated by Django 6.0.5 on 2026-06-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('layar', 'Layar / LCD'), ('baterai', 'Baterai'), ('mesin', 'Motherboard / Mesin'), ('kamera', 'Kamera'), ('konektor', 'Konektor Charger'), ('fleksibel', 'Kabel Fleksibel'), ('tombol', 'Tombol Fisik'), ('aksesoris', 'Aksesoris / Case'), ('lainnya', 'Lain-lain')], default='lainnya', max_length=20)),
                ('device_type', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('lainnya', 'Lain-lain')], default='lainnya', max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=5)),
                ('cost_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('activity_type', models.CharField(choices=[('tambah', 'Restock / Tambah'), ('pakai', 'Digunakan'), ('penyesuaian', 'Penyesuaian')], default='penyesuaian', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.sparepart')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_usages', to='core.ticket')),
            ],
        ),
    ]
