# Generated by Django 6.0.4 on 2026-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sparepart_sparepartusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
